### ISSUE TITLE
pip install Flask-RESTful doesn't bring in six

### ISSUE THREAD

**Issue by eggtree** [flask-restful/flask-restful#135]
I'm not a pip expert but I think when I pip install Flask-RESTful it should at the same time install six. Apologies if this issue is bogus I'm a python newb.

When I pip install Flask and Flask-RESTful then run my app it falls over with the following traceback unless I also pip install six.

```
Traceback (most recent call last):
  File "aca/api.py", line 2, in <module>
    from flask.ext.restful import reqparse, abort, Api, Resource
  File "/home/me/aca/aca-ex-venv/local/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/home/me/aca/aca-ex-venv/local/lib/python2.7/site-packages/flask_restful/reqparse.py", line 4, in      <module>
    import six
ImportError: No module named six
```

My venv.

```
$ pip freeze
Flask==0.10.1
Flask-RESTful==0.2.5
Jinja2==2.7.1
MarkupSafe==0.18
Werkzeug==0.9.4
argparse==1.2.1
distribute==0.6.34
itsdangerous==0.23
requests==2.0.0
wsgiref==0.1.2
```

**Comment by Al-mudather** [comment]
Try this and it will work, pip install Flask-RESTful

**Comment by MarianneRario** [comment]
> Try this and it will work, pip install Flask-RESTful

this works thanks!
