### ISSUE TITLE
ImportError (No module named 'UserDict') in Python 3

### ISSUE THREAD

**Issue by garretraziel** [flask-restful/flask-restful#192]
I am running nose tests in Python 3 and one of them is failing with ImportError.

Output is:

```
ERROR: Failure: ImportError (No module named 'UserDict')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/garret/python3-venv/lib/python3.3/site-packages/nose/failure.py", line 38, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/garret/python3-venv/lib/python3.3/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/garret/python3-venv/lib/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/garret/python3-venv/lib/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.3/imp.py", line 175, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.3/imp.py", line 114, in load_source
    _LoadSourceCompatibility(name, pathname, file).load_module(name)
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/garret/Projects/flask-restful/tests/test_fields.py", line 5, in <module>
    from flask.ext.restful.utils.ordereddict import OrderedDict
  File "/home/garret/Projects/flask-restful/flask_restful/utils/ordereddict.py", line 23, in <module>
    from UserDict import DictMixin
ImportError: No module named 'UserDict'
```

Python 3 doesn't have module named UserDict. UserDict was moved to collections and DictMixin doesn't exists. See https://stackoverflow.com/questions/11165188/how-to-achieve-the-functionality-of-userdict-dictmixin-in-python-3.

**Comment by Torxed** [comment]
I get that this is old as f**. But this is some how still an issue running latest Kali, and this is where you end up when you do some searching around. The fix:

Modify `/usr/share/responder/tools/SMBFinger/Finger.py` at the very top:
```
try:
    from collections import ORderedDict
except:
    from .odict import OrderedDict
```

Seams to be the only thing that's needed. Again, apologies for really going all Zombie on this thread, but as this is shipped with Kali and it's among the top hits on google, I'm bound to end up here again and perhaps others as well.

**Comment by P-tez** [comment]
@Torxed  Thanks, you fixed it. 

However there is another error appears "
/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:"

Do you have any idea how to fix that. 

Thanks in Advance

**Comment by freddrake** [comment]
Could use `!=` instead of `is not`.  The suggestion in the warning message is spot on.

**Comment by P-tez** [comment]
@freddrake , please accept my simple questions as i am not familiar with python. 

I am using Multirelay for relaying NTLM hash on the traget machine 
./MultiRelay.py -t x.x.x.x -u ALL (this is the command in kali)
and it give me the mentioned error "/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if data.find("NTLM") is not -1:"
then start Relay tool but no hashed relayed
Do i have to change specific python file related to tool in order to fix error ?

**Comment by freddrake** [comment]
No worries, @P-tez!

Since it's a warning, it shouldn't actually affect operation.  If it isn't actually working for you, that's likely not the reason.

**Comment by Torxed** [comment]
@P-tez It's also just a warning, probably safe to ignore unless there's an actual runtime error with it. Should be fixed upstream tho :)

**Comment by P-tez** [comment]
Thanks alot @freddrake  & @Torxed  :)
