### ISSUE TITLE
JSON request body with non-object as root throws an exception

### ISSUE THREAD

**Issue by tgwizard** [flask-restful/flask-restful#411]
This failing test case proves the point:

```python
def test_get_json_location_with_string_as_root(self):
    app = Flask(__name__)

    parser = RequestParser()
    parser.add_argument("foo", location="json")

    with app.test_request_context('/bubble', method="post",
                                  data=json.dumps("this is a string with foo in it"),
                                  content_type='application/json'):
        args = parser.parse_args()
        self.assertEquals(args['foo'], None)
```

This is the traceback:

```
======================================================================
ERROR: test_get_json_location_with_string_as_root (tests.test_reqparse.ReqParseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/adam/code/flask-restful/tests/test_reqparse.py", line 246, in test_get_json_location_with_string_as_root
    args = parser.parse_args()
  File "/Users/adam/code/flask-restful/flask_restful/reqparse.py", line 261, in parse_args
    value, found = arg.parse(req)
  File "/Users/adam/code/flask-restful/flask_restful/reqparse.py", line 158, in parse
    values = [source.get(name)]
AttributeError: 'unicode' object has no attribute 'get'
```

The problem is quite simple: `Argument.parse` fetches the source (which is from the JSON request body). Then a check is done `if name in source`, which is true here, since `'foo' in 'this is a string with foo in it'`. Then `values = [source.get(name)]` fails, since `source` is a `unicode` string, not a dict.

I'm not sure of the best way to solve this, that's why I don't submit a PR. One idea could be to enforce that the `source` returned by `Argument.source` is a dict-like object. Do we want to support arrays in the RequestParser?

**Comment by joshfriend** [comment]
`reqparse` was intended to work only with objects. It doesn't really make any sense to try to parse arguments from a plain string. List, maybe, but that's also outside the current capabilities, and there are better ways to parse lists of objects using a library like `marshmallow`, and because of #335, I don't think we want to add that feature.

I think the best way to handle this will be to catch the exception and raise a `BadRequest` so the api would return a 400 error instead of a 500 error.

**Comment by tgwizard** [comment]
Yes, I agree with that being the way forward. A simple check in `Argument.source` that `instanceof(source, dict)` is true and throwing a `BadRequest` / aborting with 400 otherwise would be suitable, I think.

**Comment by davidavdav** [comment]
Hello, 

I get a similar error in the request parser when posting valid json, but not a dict object with `data='"a"'`. 
```
  File "/Library/Python/2.7/site-packages/flask_restful/reqparse.py", line 294, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/Library/Python/2.7/site-packages/flask_restful/reqparse.py", line 154, in parse
    source = self.source(request)
  File "/Library/Python/2.7/site-packages/flask_restful/reqparse.py", line 102, in source
    values.update(value)
  File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 562, in update
    for key, value in iter_multi_items(other_dict):
ValueError: need more than 1 value to unpack
```
So an invalid json object returns a BadRequest, but a valid json that isn't a dict crashes the reqparse parser.
