### ISSUE TITLE
api.url_for() fails with endpoints specified by a string

### ISSUE THREAD

**Issue by CnlPepper** [flask-restful/flask-restful#494]
I use the a common Resource class for a number of routes and therefore specify an endpoint manually. Unfortunately it appears that the api.url_for() does not accept a string endpoint, only a Resource. It is therefore not possible to generate a url for manually specified endpoints.

Could you modify the method to accept either a Resource object or a string endpoint name?

Apologies if this is already fixed, I've not seen anything in the logs.

**Comment by joshfriend** [comment]
`flask_restful.url_for()` basically just [calls `flask.url_for()` with `resource.endpoint`](https://github.com/flask-restful/flask-restful/blob/7538b00b2d9b33dd2d88340e740681eafd9d056a/flask_restful/__init__.py#L482). Can you try using the `url_for()` from Flask instead?

**Comment by CnlPepper** [comment]
Hello, thanks for the reply, I've tested the flask url_for() asking for a url for the following endpoint:

```
api.add_resource(DiscreteCollection, PREDEFINED_ROUTE + "/equilibrium/", resource_class_args=(["timeslice"], ), endpoint="equilibrium")
```

which results in an exception. The error below is from a  test request context, the result is the same for a real request.

```
Traceback (most recent call last):
  File "/home/ameak/code/dashboard/graphing-service/runserver.py", line 1, in <module>
    from spiro import app
  File "/home/ameak/code/dashboard/graphing-service/spiro/__init__.py", line 1, in <module>
    from .app import app
  File "/home/ameak/code/dashboard/graphing-service/spiro/app.py", line 98, in <module>
    print(url_for("equilibrium"))
  File "/usr/local/depot/python335_modules/site-packages/Flask-0.10.1-py3.3.egg/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/depot/python335_modules/site-packages/Flask-0.10.1-py3.3.egg/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/depot/python335_modules/site-packages/Flask-0.10.1-py3.3.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/depot/python335_modules/site-packages/Flask-0.10.1-py3.3.egg/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/local/depot/python335_modules/site-packages/Werkzeug-0.10.4-py3.3.egg/werkzeug/routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
werkzeug.routing.BuildError: ('equilibrium', {}, None)
```

The DiscreteCollection class is used in multiple places in this api so I can't simply reference the object.

**Comment by joshfriend** [comment]
Looking back through the [issues list for `BuildError`](https://github.com/flask-restful/flask-restful/search?q=BuildError&type=Issues&utf8=%E2%9C%93), i think [#266](https://github.com/flask-restful/flask-restful/issues/266#issuecomment-46678118) might have some useful info. That person fixed the issue by making sure the endpoint string started with `"."`.

My other guess is that your endpoint route takes parameters, but you don't provide any when calling `url_for()`

**Comment by CnlPepper** [comment]
Thanks joshfriend, I just tried adding a "." before the endpoint name. It now appears to works correctly. This does seem to be very unintuitive though - an  endpoint named "blah" requires ".blah" to reference it!

Do you think it would break anything if the flask-restful api.url_for() automatically added the "." to string endpoints?

**Comment by joshfriend** [comment]
[It looks to me like Flask doesn't do anything with auto-adding `"."`](https://github.com/mitsuhiko/flask/blob/b528b2ffe30e72a4dc19a54ba080d33278b8b6ba/flask/helpers.py#L186-L320), so I don't think Flask-RESTful should either.
