### ISSUE TITLE
Unicode literals don't like in Python 2

### ISSUE THREAD

**Issue by skion** [flask-restful/flask-restful#502]
When using `unicode_literals`, there seems to be no way to define a custom resource endpoint in a way that works with both Python 2 and Python 3.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import flask
import flask_restful

ENDPOINT = "test123"

app = flask.Flask(__name__)
api = flask_restful.Api(app)


class TestAPI(flask_restful.Resource):
    pass


api.add_resource(TestAPI, "/test", endpoint=ENDPOINT)
```
The above example works with Py3, but not Py2:

```
TypeError: __name__ must be set to a string object
```
To make it work in Py2, the endpoint needs an explicit bytestring type:

```python
ENDPOINT = b"test123"
```
But doing so breaks the code under Py3 again.

**Comment by joshfriend** [comment]
I'm afraid nothing can be done in this case. If you look closely at the stacktrace:
```python
Traceback (most recent call last):
  File "502.py", line 18, in <module>
    api.add_resource(TestAPI, "/test", endpoint=ENDPOINT)
  File "/Users/josh/git/flask-restful/flask_restful/__init__.py", line 407, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)
  File "/Users/josh/git/flask-restful/flask_restful/__init__.py", line 447, in _register_view
    **resource_class_kwargs))
  File "/Users/josh/git/flask-restful/env/py27/lib/python2.7/site-packages/flask/views.py", line 98, in as_view
    view.__name__ = name
TypeError: __name__ must be set to a string object
```
You will see that the error is thrown in flask and not flask-restful. Also, assigning a unicode string to the `__name__` property of a python2 object appears to be a known limitation: http://bugs.python.org/issue7688

**Comment by skion** [comment]
Ah right, I'll work around it then...
