### ISSUE TITLE
reqparse - unexpected error message

### ISSUE THREAD

**Issue by AbdealiJK** [flask-restful/flask-restful#556]
Hi,

I was trying to use reqparse to ensure that a user gives `username` and `password` fields to a Resource with POST data.

I tried
```
class RegisterResource(Resource):
    def post(self):
        parser = reqparse.RequestParser()
        parser.add_argument('username', type=str)
        args = parser.parse_args()
```

According to the current code that I see, this should search in `request.json` first, then `request.values` and should merge the results from both. But right now, I keep getting:
```
{
    "message": "The browser (or proxy) sent a request that this server could not understand."
}
```

It seems that flask is raising a BadRequest in `on_json_loading_failed` which is being called when `reqparse` does `getattr(request, l, None)` with `l='json'` as there is no JSON (`json.loads("")` throws ValueError)

I'm currently using `location='values'` and the error shown is fine. So, the "checking if request.json exists" is causing the issue.

**Comment by joshfriend** [comment]
See #510

**Comment by lucacome** [comment]
The other issue referenced here is on a GET, but I'm getting this error on a POST (like @AbdealiJK ).
Also in the docs says that you can set multiple location like `location=['headers', 'values']`, but that gives this error:

```2016-11-29 22:57:25,822 [18] 18_10017 Handled exception "unhashable type: 'list'" while processing /1.0/swagger.json GET
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 750, in get
    return self.api.__schema__
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 451, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 167, in as_dict
    paths[extract_path(url)] = self.serialize_resource(ns, resource, url, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 296, in serialize_resource
    doc = self.extract_resource_doc(resource, url)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 233, in extract_resource_doc
    method_params = self.expected_params(method_doc)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 247, in expected_params
    parser_params = dict((p['name'], p) for p in expect.__schema__)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/reqparse.py", line 396, in __schema__
    param = arg.__schema__
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/reqparse.py", line 264, in __schema__
    'in': LOCATIONS.get(self.location, 'query')
TypeError: unhashable type: 'list'```
and swagger can't load the UI, giving a 500

**Comment by joshfriend** [comment]
@lucacome it's clearly an error with the flask extension you are using (flask-restplus). You are actually not using flask-restful _at all_.
