### ISSUE TITLE
teardown_request isn't passed exceptions

### ISSUE THREAD

**Issue by rgant** [flask-restful/flask-restful#571]
I am trying to use Flask's [teardown_request](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.teardown_request) feature to commit or rollback the DB transaction based on if there was an exception while handling the request. However it doesn't appear that teardown request ever gets the exception that is raised in the request. 

``` python
def _teardown_request(exc):
    """
    Commit the current Database Transaction
    :param Exception or None exc: Exception handling this request
    """
    if exc:
        # Got an exception, so rollback transaction
        logger = logging.getLogger(__name__)
        logger.error("Got Exception in request, rollback transaction. %s", exc)
        db.rollback()
    else:
        db.commit()

    db.close()

blueprint.teardown_request(_teardown_request)
```

However this exception didn't rollback the request:

```
ERROR:app:log_exception:1423:Exception on /v3/accounts/me/investments [GET]
Traceback (most recent call last):
  File "/Users/rgant/api/venv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rgant/api/venv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rgant/api/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/rgant/api/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/rgant/api/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/rgant/api/tiapi.py", line 39, in auth_wrap
    return func(*args, **kwargs)
  File "/Users/rgant/api/investment.py", line 38, in get
    raise Exception('Github Issue Example')
Exception: Github Issue Example
INFO:db:commit:49:Commit Session.
INFO:db:close:43:Remove Scoped Session.
WARNING:conftest:method_log:89:Non Successful Status Code (500). Body: b'{"message": "Internal Server Error"}\n'
```

Any suggestions where I am going wrong trying to set this up?

**Comment by saschwarz** [comment]
Maybe you need PRESERVE_CONTEXT_ON_EXCEPTION in debug mode per this SO answer: http://stackoverflow.com/a/33284980/457935 (?)

**Comment by rgant** [comment]
Not really seeing what is being done differently in that SO ticket than my setup above. But there is a bunch of stuff there so maybe I just missed it.

**Comment by bhirbec** [comment]
I'm trying to do the exact thing than @rgant and have the same issue (exception is always `None` even if the handler raised one). Does anyone know a fix for this by any chance?

**Comment by jkryanchou** [comment]
I have met same issue, Is there any solution on it? @rgant
