### ISSUE TITLE
Exceptions thrown within Flask-RESTful apps getting executed instead of thrown?

### ISSUE THREAD

**Issue by bhechinger** [flask-restful/flask-restful#582]
So this has been extremely frustrating. Every single exception thrown within our Flask-RESTful code appears to be getting caught and executed rather than caught and thrown by Flask-RESTful.

python: 2.7.10
Flask-RESTful: 0.3.5

Example output:

```
127.0.0.1 - - [21/Apr/2016 14:28:41] "POST /lc-cluster/create HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask_RESTful-0.3.5-py2.7.egg/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask_RESTful-0.3.5-py2.7.egg/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/wrappers.py", line 847, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/bheching/projects/virtualenvs/vmRapidDeploy/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'NoOptionError' object is not callable
```

**Comment by CristianoYL** [comment]
Hi @bhechinger, I had the same issue. What I did is to add this line in my `app.py`:
```app.config['PROPAGATE_EXCEPTIONS'] = True```
And it will allow the error to propagate.
