### ISSUE TITLE
GET randomly throws encode error

### ISSUE THREAD

**Issue by soggychips** [flask-restful/flask-restful#587]
The error arises out of a simple example that can be replicated.

```
class Articles(Resource):
  def get(self, **kwargs):
    results = ({'active': 1, 'article_id': u'431397', 'id': 1L, 'title': u'Canada Fire'},
					{'active': 1, 'article_id': u'584341', 'id': 4L, 'title': u'Smoking Age Raised in Cali'},
					{'active': 1, 'article_id': u'456268', 'id': 43L, 'title': u'NYPD Fires Chief'},
					{'active': 1, 'article_id': u'455264', 'id': 50L, 'title': u'Ex Machina Wins Best P...'})
    return results
```

The above works totally fine, 100% of the time.

All I do to get the bug is to remove one of the dicts from the ```results``` variable, as such:

```
class Articles(Resource):
  def get(self, **kwargs):
    results = ({'active': 1, 'article_id': u'431397', 'id': 1L, 'title': u'Canada Fire'},
					{'active': 1, 'article_id': u'584341', 'id': 4L, 'title': u'Smoking Age Raised in Cali'},
					{'active': 1, 'article_id': u'455264', 'id': 50L, 'title': u'Ex Machina Wins Best P...'})
    return results
```

and I get this traceback 100% of the time:

```
Traceback (most recent call last):
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 481, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 510, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask_restful/representations/json.py", line 22, in output_json
    resp = make_response(dumped, code)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/helpers.py", line 183, in make_response
    return current_app.make_response(args)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/flask/app.py", line 1574, in make_response
    rv = self.response_class(rv, headers=headers, status=status)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/werkzeug/wrappers.py", line 778, in __init__
    self.status = status
  File "/opt/primeapi/venv/lib/python2.7/site-packages/werkzeug/wrappers.py", line 884, in _set_status
    self._status = to_native(value)
  File "/opt/primeapi/venv/lib/python2.7/site-packages/werkzeug/_compat.py", line 117, in to_native
    return x.encode(charset, errors)
AttributeError: 'dict' object has no attribute 'encode'
```

Dumping x gives me ```{'active': 1, 'article_id': u'584341', 'id': 4L, 'title': u'Smoking Age Raised in Cali'}```. It's understood that dict objects don't have an encode method, but the difference between the two return statements seems intrinsically non-existent.

**Comment by soggychips** [comment]
forcing the tuple to be a list seems to be a workaround...

``` return list(results) ```

Still, there seems to be a bug here.

Cheers!

**Comment by neilsh** [comment]
Which version of werkzeug did this occur on?

**Comment by songxiaowei112** [comment]
All versions are, this is not a mistake, this is the return value of the wrong type.

**Comment by soggychips** [comment]
I don't see how the length of a tuple affects the return type being correct or not. 

Thanks,

Jake

**Comment by joshfriend** [comment]
> If a tuple is returned the items in the tuple can provide extra information. Such tuples have to be in the form `(response, status, headers)` or `(response, headers)` where at least one item has to be in the tuple. The status value will override the status code and headers can be a list or dictionary of additional header values.

(http://flask.pocoo.org/docs/0.11/quickstart/#about-responses)

> Flask-RESTful understands multiple kinds of return values from view methods. Similar to Flask, you can return any iterable and it will be converted into a response, including raw Flask response objects. Flask-RESTful also support setting the response code and response headers using multiple return values, as shown below

(https://flask-restful.readthedocs.io/en/0.3.5/quickstart.html#resourceful-routing)

"multiple return" in python just means the function returns a tuple (as you did above)
