### ISSUE TITLE
UnicodeEncodeError when argument's choices contain unicode

### ISSUE THREAD

**Issue by ST9527** [flask-restful/flask-restful#593]
My code looks like below:

```
STATUS = (u'未审核', u'审核通过', u'未施工', u'正在施工', u'施工完成')

class WorkBill(Resource):
    def __init__(self):
        self.parser = reqparse.RequestParser()
        self.parser.add_argument('status', type=unicode, choices=STATUS, required=True, location='json',  help='工单状态出错: {error_msg}')
``` 

When the argument was one of the `STATUS`,this went well.But when the argument is not one of the `STATUS`,it throws error like this

```
Traceback (most recent call last):
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/long/yx/git/eshore/eshore/views/workbill.py", line 60, in patch
    args = self.parser.parse_args()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 301, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 199, in parse
    value)), bundle_errors)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 145, in handle_validation_error
    error_msg = self.help.format(error_msg=error_str) if self.help else error_str
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

It is because `error_str` is a unicode string, but `self.help` is a str. So I try to change `help` to unicode like this 

>         self.parser.add_argument('status', type=unicode, choices=STATUS, required=True, location='json',  help=u'工单状态出错: {error_msg}')

But it throws error like this 

```
Traceback (most recent call last):
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/long/yx/git/eshore/eshore/views/workbill.py", line 60, in patch
    args = self.parser.parse_args()
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 301, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 199, in parse
    value)), bundle_errors)
  File "/Users/long/.pyenv/versions/myenv2/lib/python2.7/site-packages/flask_restful/reqparse.py", line 146, in handle_validation_error
    msg = {self.name: "{0}".format(error_msg)}
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```

This time it's because `error_msg` is a unicode and **"{0}".format(error_msg)** will cause error.

At the end, I had to add

> if args['status'] in STATUS:

in the class method.

It's this a bug?Please fixed it. Maybe it's time switch to Python 3 ;(

**Comment by tdpsk** [comment]
I did some research, this has been reported in #508 and fixed in #564. I assume you don't want to wait for this to appear upstream, so I recommend you apply it via a git patch if you need it urgently. I have created a [patch from the pull request](https://goo.gl/eRg8fh) for your convenience.
