### ISSUE TITLE
AttributeError: 'Blueprint' object has no attribute 'view_functions'

### ISSUE THREAD

**Issue by eromoe** [flask-restful/flask-restful#700]
I have code like:

```
api = Blueprint('api', __name__, url_prefix='/api')
api_wrap = Api(api)


@api_wrap.resource('/corpus/')
class CorpusListPage(Resource):
    def get(self):
        page_size = request.args.get('page_size', 10)
        page_num = request.args.get('page_num', 1)
        query = db.session.query(Corpus)
        result = query.paginate(page_num, page_size)
        # total = result.total
        # record_items = result.items
        return result, 200 if result else 404

```

Got error:

```
Traceback (most recent call last):
  File "app.py", line 133, in <module>
    app = create_app('debug')
  File "app.py", line 32, in create_app
    configure_blueprints(app)
  File "app.py", line 88, in configure_blueprints
    from api import api
  File "E:\Project\allproject_git\annotator-server\src\api\__init__.py", line 2, in <module>
    from views import api
  File "E:\Project\allproject_git\annotator-server\src\api\views.py", line 24, in <module>
    class CorpusListPage(Resource):
  File "D:\Python27\lib\site-packages\flask_restful\__init__.py", line 416, in decorator
    self.add_resource(cls, *urls, **kwargs)
  File "D:\Python27\lib\site-packages\flask_restful\__init__.py", line 396, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)
  File "D:\Python27\lib\site-packages\flask_restful\__init__.py", line 426, in _register_view
    if endpoint in app.view_functions.keys():
AttributeError: 'Blueprint' object has no attribute 'view_functions'
```

env:
flask-0.12.2
Flask-RESTful (0.3.4)

**Comment by eromoe** [comment]
update to flask-restful-0.3.6 solved.
