### ISSUE TITLE
BuildError. Did you forget to specify values

### ISSUE THREAD

**Issue by mliker** [flask-restful/flask-restful#701]
Hi,

I have the following simple flask restful service, however I am not able to make it work due to the below error.

I read over similar issues here however none seem to have run into the same error as below.

Appreciate your help with this.

restful service:
```python
import os
from flask import Flask, abort
from flask_restful import Resource, Api, reqparse, fields, marshal
from flask_pymongo import PyMongo, GridFS
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename
import logging
import zipfile


# Setup flask app
app = Flask(__name__)
app.config.update(ERROR_404_HELP=False)
api = Api(app)

# Setup logging
stream_handler = logging.StreamHandler()
stream_handler.setFormatter(logging.Formatter(
    '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'))
app.logger.addHandler(stream_handler)
app.logger.setLevel(os.environ.get("LOGLEVEL", "INFO").upper())

# MongoDB set up
mongo = PyMongo(app)

# Request argument parsing
reqparser = reqparse.RequestParser()
reqparser.add_argument('custom_component', required=True, type=FileStorage,
                    location='files')

component_fields = {
    'filename': fields.String,
    'upload_date': fields.DateTime,
    'uri': fields.Url('component', absolute=True)
}


def validate_component(zipfile):
    return True


class CustomComponentListService(Resource):
    def __init__(self):
        self.fs = GridFS(mongo.db)

    def post(self):
        self.args = reqparser.parse_args()
        component_zip = self.args["custom_component"]
        filename = secure_filename(component_zip.filename)
        app.logger.debug("Received file: {0}".format(filename))

        if validate_component(component_zip):
            mongo.save_file(filename, component_zip)
            # Return nice repr of uploaded file
            return {'component': marshal(self.fs.get_last_version(filename), component_fields)}, 201
        else:
            return {"message": "Custom component archive is invalid"}, 400

    def get(self):
        return {"components": [marshal(component, component_fields) for component in self.fs.find()]}


class CustomComponentService(Resource):
    def __init__(self):
        self.fs = GridFS(mongo.db)

    def get(self, filename):
        filename = secure_filename(filename)
        if self.fs.exists(filename=filename):
            return {"component": marshal(self.fs.get_last_version(filename=filename), component_fields)}
        else:
            abort(404, "No such file")

    def put(self, filename):
        self.args = reqparser.parse_args()
        filename = secure_filename(filename)
        if self.fs.exists(filename=filename):
            mongo.db.save_file()
            return {"component": marshal(self.fs.get_last_version(filename=filename), component_fields)}
        else:
            abort(404, "No such file")

    def delete(self, filename):
        filename = secure_filename(filename)
        if self.fs.exists(filename=filename):
            for f in self.fs.find({"filename": filename}):
                fs.delete(f._id)
            return  {'result': True}
        else:
            abort(404, "No such file")


api.add_resource(CustomComponentListService, '/components',
                 endpoint='components')
api.add_resource(CustomComponentService, '/components/<filename>',
                 endpoint='component')


if __name__ == "__main__":
    app.run()
```

stacktrace:
```python
127.0.0.1 - - [19/Sep/2017 10:05:37] "GET /components HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/custom_components.py", line 61, in get
    return {"components": [marshal(component, component_fields) for component in self.fs.find()]}
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 648, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/__init__.py", line 647, in <genexpr>
    for k, v in fields.items())
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask_restful/fields.py", line 307, in output
    o = urlparse(url_for(endpoint, _external=self.absolute, **data))
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/m_liker/Documents/Projects/clientIO/grid-infra/custom_components/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'component' with values ['_GridOut__buffer', '_GridOut__chunks', '_GridOut__files', '_GridOut__position', '_file']. Did you forget to specify values ['filename']?
```

**Comment by mliker** [comment]
What is really puzzling me is that the object that enters marshalling is different from the object that werkzueg complains about.

at line 
```python
return {"components": [marshal(component, component_fields) for component in self.fs.find()]}
```
dump(component) shows (partial):
![pasted image at 2017_09_19 01_13 pm](https://user-images.githubusercontent.com/1681893/30589852-648983ee-9d3c-11e7-949c-95f178a9586e.png)

whereas at the "raise BuildError(endpoint, values, method, self)" line in debugger the values contains:
```python
>>> values
{'_GridOut__position': 0, '_GridOut__files': Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=True, connect=True, replicaset=None), u'custom_components'), u'fs.files'), '_file': {u'contentType': u'application/zip', u'chunkSize': 261120, u'filename': u'zipdir.zip', u'length': 374,   }, '_GridOut__chunks': Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=True, connect=True, replicaset=None), u'custom_components'), u'fs.chunks'), '_GridOut__buffer': ''  }
```

**Comment by joshfriend** [comment]
When you define an URL field (`fields.Url('component', absolute=True)`) the marshaller is taking the object and [dumping it to a dictionary of it's property values](https://github.com/flask-restful/flask-restful/blob/ce9133873708effcde50d2e65b651b37ff06d376/flask_restful/fields.py#L305). Then, it calls `url_for()` with the endpoint you specified (`'component'`) and [the fields of the object as the arguments to the endpoint](https://github.com/flask-restful/flask-restful/blob/ce9133873708effcde50d2e65b651b37ff06d376/flask_restful/fields.py#L307).

The route you are trying to build an url for (`'/components/<filename>'`) has 1 argument: `filename`. However, your object does not have a `filename` property, so `url_for` lacks enough information to build the url (hence the error `Did you forget to specify values ['filename']?`).

Your object has a `_file` property which is an object that has a `filename` property, perhaps you meant to use this field? If so try defining the field like this:

```python
component_fields = {
    'filename': fields.String,
    'upload_date': fields.DateTime,
    'uri': fields.Url('component', absolute=True, attribute='_file')  # <- note the `attribute` parameter
}
```

**Comment by mliker** [comment]
Ah, thanks I get it.

However, why is there a difference between component attributes and the values list which should be the attributes of component? It seems to me like only a subset of attributes is being passed down to werkzeug

**Comment by mliker** [comment]
@joshfriend 

Unfortunately your suggestion of adding the attribute keyword does not work with the current codebase.

```python
(custom_components) Marcels-MacBook-Pro:custom_components m_liker$ LOGLEVEL=debug FLASK_DEBUG=1 python custom_components.py 
Traceback (most recent call last):
  File "custom_components.py", line 35, in <module>
    'uri': fields.Url('component', attribute="_file", absolute=True)
TypeError: __init__() got an unexpected keyword argument 'attribute'
```

My guess is that since Url inherits from Raw and overrides its __init__ method with different signature, it does not account for extra kwargs hence attribute kwarg can not be used during initialisation.
FormattedString is also overriding super.__init___ with different signature and not accepting any additional kwargs from Raw.__init__ signature.

Can I open a PR to fix this?

This will work however:

```python
fields = {
'uri': fields.Url('component', absolute=True)
}

fields["uri"].attribute = "attribute_name"
```

For me however, it still leaves the question of the difference between component attributes at marshalling and url_for values open.

**Comment by mliker** [comment]
I will close this since my initial question was answered
