### ISSUE TITLE
fields.List does not play well with fields.Url for non-dictionary objects

### ISSUE THREAD

**Issue by matthewstory** [flask-restful/flask-restful#714]
I have a model `Group` that works nicely with `fields.Url` when serialized on a related type:

```
class OwnedObject(Resource):
    resource_type_map = {
        # ...
        "group": fields.Url("group_api"),
    }

    @marshal_with(resource_type_map)
    def get(self, owned_object_id):
        # returns { "group": "group/url/id" }
        return OwnedObject.query.get(owned_object_id)
```

While this works with one URL, it doesn't work with a List of URLs:

```
class OwnedObject(Resource):
    resource_type_map = {
        # ...
        "groups": fields.List(fields.Url("group_api")),
    }

    @marshal_with(resource_type_map)
    def get(self, owned_object_id):
        return OwnedObjectModel.query.get(owned_object_id)
```

Throws an error like this:

```
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/matt/.local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/__init__.py", line 684, in wrapper
    return marshal(resp, self.fields, self.envelope)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/__init__.py", line 640, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/__init__.py", line 639, in <genexpr>
    for k, v in fields.items())
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/fields.py", line 200, in output
    return self.format(value)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/fields.py", line 193, in format
    for idx, val in enumerate(value)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/fields.py", line 193, in <listcomp>
    for idx, val in enumerate(value)
  File "/usr/local/lib/python3.5/dist-packages/Flask_RESTful-0.3.5-py3.5.egg/flask_restful/fields.py", line 313, in output
    raise MarshallingException(te)
flask_restful.fields.MarshallingException: url_for() argument after ** must be a mapping, not list
```

Digging into this it looks like the problem is that because the `GroupModel` is not a dictionary, the values `0` and the list of group objects are passed to fields.Url from the `fields.List:format` function (fields.py:185):

```
185         return [
186             self.container.output(idx,
187                 val if (isinstance(val, dict)
188                         or (self.container.attribute
189                             and hasattr(val, self.container.attribute)))
190                         and not isinstance(self.container, Nested)
191                         and not type(self.container) is Raw
192                     else value)
193             for idx, val in enumerate(value)
194         ]
```

I'm happy to provide a fix, but I don't understand the code base deeply enough to get why this series clauses is here in the first place? It seems like rather than checking to see if the instance of `val` is a `dict`, we should check to see if the `to_marshallable_type` is a `dict` or not. But again, not sure.

**Comment by viveksoundrapandi** [comment]
@matthewstory I couldn't replicate the issue you were mentioning about. I had the following setup:
`import collections

import json

from flask_restful import fields, marshal

from flask import request, url_for

schema = {
    "group": fields.List(fields.Url(".ownedobject"))
}

data={ "group": [url_for(".ownedobject"), url_for(".ownedobject")] }

print(json.dumps(marshal(data, schema)))`
