### ISSUE TITLE
Flask attempting to serialize as JSON despite mimetype=text/plain

### ISSUE THREAD

**Issue by guillochon** [flask-restful/flask-restful#726]
I have an API that I'm posting `application/json` data to that I want to return `text/plain` from. I'm getting the following error:

    TypeError: Object of type 'Response' is not JSON serializable

Even though I am *explicitly* setting `text/plain` as the mimetype:

    return Response(ret_str, mimetype='text/plain')

My post looks like this:

    headers = {"Content-Type":"application/json", "Accept":"text/plain"}
    r = requests.post(url, data = json.dumps(data), headers = headers)

Am I doing something wrong here? How can I get it to return `text/plain` without choking?

Full backtrace

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/root/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/root/miniconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
        return self.make_response(data, code, headers=headers)
      File "/root/miniconda3/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
        resp = self.representations[mediatype](data, *args, **kwargs)
      File "/root/miniconda3/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
        dumped = dumps(data, **settings) + "\n"
      File "/root/miniconda3/lib/python3.6/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/root/miniconda3/lib/python3.6/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/root/miniconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/root/miniconda3/lib/python3.6/json/encoder.py", line 180, in default
        o.__class__.__name__)
    TypeError: Object of type 'Response' is not JSON serializable

**Comment by guillochon** [comment]
Pretty stumped by this and haven't gotten anywhere since originally posting. Any thoughts @joshfriend?

**Comment by RaydelMiranda** [comment]
Have the same problem here.
