### ISSUE TITLE
Failed test case when combined with flask-jwt-extended

### ISSUE THREAD

**Issue by itsjef** [flask-restful/flask-restful#803]
Hi, I am having good luck with Flask-Restful so far, but when I tried to combine your package with Flask-JWT-Extended, I ran into the issue of failed test cases.

Here is a simplified test case to demonstrate the problem:

**Test cases:**

```python
# test_flask.py (TESS PASSED)
import pytest
from flask import Flask, jsonify
from flask_jwt_extended import JWTManager, jwt_required


@pytest.fixture(scope="function")
def app():
    app = Flask(__name__)
    app.config["JWT_SECRET_KEY"] = "foobarbaz"
    JWTManager(app)

    @app.route("/protected", methods=["GET"])
    @jwt_required
    def access_protected():
        return jsonify(foo="bar")

    return app


def test_missing_headers(app):
    test_client = app.test_client()

    response = test_client.get("/protected", headers=None)
    assert response.status_code == 401
    assert response.get_json() == {"msg": "Missing Authorization Header"}
```

```python
# test_flask_restful.py (TEST ERROR)
import pytest
from flask import Flask, jsonify
from flask_restful import Resource, Api
from flask_jwt_extended import JWTManager, jwt_required


@pytest.fixture(scope="function")
def app():
    app = Flask(__name__)

    app.config["JWT_SECRET_KEY"] = "foobarbaz"
    JWTManager(app)

    api = Api(app)

    class ProtectedResource(Resource):
        method_decorators = [jwt_required]

        def get(self):
            return jsonify(foo="bar")

    api.add_resource(ProtectedResource, "/protected")

    return app


def test_missing_headers(app):
    test_client = app.test_client()

    response = test_client.get("/protected", headers=None)
    assert response.status_code == 401
    assert response.get_json() == {"msg": "Missing Authorization Header"}
```

**Result:**
```
================================================ test session starts =================================================
platform linux -- Python 3.6.7, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /tmp/test-x, inifile:
collected 2 items                                                                                                    

test-flask.py .                                                                                                [ 50%]
test-flask-restful.py F                                                                                        [100%]

====================================================== FAILURES ======================================================
________________________________________________ test_missing_headers ________________________________________________

app = <Flask 'test-flask-restful'>

    def test_missing_headers(app):
        test_client = app.test_client()
    
        response = test_client.get("/protected", headers=None)
>       assert response.status_code == 401
E       assert 500 == 401
E        +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code

test-flask-restful.py:31: AssertionError
------------------------------------------------- Captured log call --------------------------------------------------
app.py                    1761 ERROR    Exception on /protected [GET]
Traceback (most recent call last):
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    verify_jwt_in_request()
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request                                                                                                              
    jwt_data = _decode_jwt_from_request(request_type='access')
  File "/tmp/test-x/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 291, in _decode_jwt_from_request                                                                                                          
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
========================================= 1 failed, 1 passed in 0.20 seconds =========================================
```

Noted that everything stills works perfectly if I make API calls to the server.

**Comment by itsjef** [comment]
By explicitly setting `app.config['PROPAGATE_EXCEPTIONS'] = True` or just set `app.config['TESTING'] = True`, I managed to resolve the issue :D

**Comment by joshfriend** [comment]
Looks like you intended to close this, please let me know if that's incorrect

**Comment by 3awny** [comment]
please see my stackoverflow post similar to this. Im unable to resolve still https://stackoverflow.com/questions/75235933/flask-jwt-extended-exceptions-noauthorizationerror-missing-authorization-header
