### ISSUE TITLE
Decorator cors.crossdomain cant't work with marshal_with when returning a list of object

### ISSUE THREAD

**Issue by lixianwen** [flask-restful/flask-restful#854]
Hi, as the title say, decorator @cors.crossdomain cant't work with @marshal_with when returning a list of object.

Flask             1.1.1     
Flask-RESTful     0.3.7 

Here is my snippet as follow
```
(env) [root@localhost ~]# cat api.py 
#!/usr/bin/env python

from flask import Flask
from flask_restful import Resource, Api
from flask_restful import reqparse
from flask_restful import fields, marshal_with
from flask_restful.utils import cors

app = Flask(__name__)
api_bp = Blueprint('api', __name__)
api = Api(api_bp)

res = {'name': fields.String}


class TestDetail(Resource):
#    decorators = [marshal_with(res), cors.crossdomain(origin='*')]

    @cors.crossdomain(origin='*')
    @marshal_with(res)
    def post(self):
        print(self.__class__.__name__)
        args = parser.parse_args()
        return [{'id': '5e008e1dbb69f22e8277ccae',
                   'name': 'local_minion',
                   'mid': 'local_minion',
                   'used': [30011],
                   'cap': 15}]


api.add_resource(TestDetail, '/test')
app.register_blueprint(api_bp)

parser = reqparse.RequestParser()
parser.add_argument('name')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
```

When I use marshal_with decorator or didn't use them both, it works well. 

For making a cors request, I use cors module from flask_restful.utils. It works well even combine with  @marshal_with when return a dict. But when returning a list of object, an exception raised
```
192.168.86.128 - - [08/Jan/2020 19:28:00] "POST /test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/root/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/env/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/env/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/root/env/lib/python3.6/site-packages/flask_restful/utils/cors.py", line 35, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/root/env/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/root/env/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
```

A view decorated by marshal_with would return a OrderedDict, @marshal_with would work first and @cors.crossdomain wraps it later.(Am i wrong?)

Beside, it that a bad idea by wrap a method directly in Flask? But I seen the flask restful [document](https://flask-restful.readthedocs.io/en/latest/fields.html) show this way.

Finally, refer this [pull request](https://github.com/flask-restful/flask-restful/pull/131), I found an Imperfect way to fix this issue, that is, add the decorator in a list to the relevant parameter in the Api instance, which also mean than all router can open for a cors request.

Am I missing something ?

**Comment by joshfriend** [comment]
I suggest using [Flask-CORS](https://flask-cors.readthedocs.io/en/latest/) instead. I've never used `flask_restful.cors` but Flask-CORS has worked well for me in the past

**Comment by lixianwen** [comment]
> 
> 
> I suggest using [Flask-CORS](https://flask-cors.readthedocs.io/en/latest/) instead. I've never used `flask_restful.cors` but Flask-CORS has worked well for me in the past

Thanks for response! Since Flask-CORS extension has the same functionality as `flask_restful.cors` show about. For instance, enables cors support on all routes, also contains a decorator for specific router. But it has the same compatibility problem with @marshal_with when returning a list of object

**Comment by zgoda** [comment]
It fails on itself, even when `marshal_with` is not used.

**Comment by lixianwen** [comment]
Finally, I use nginx proxy for forward requests from the front end when I deploy it to the product environment.
